class StringRunner
{
	public static void main(String [] args)
	{
		String message1="Hello everyone.";
		String drink="Drink coffee.";
		String eat="Eat your food.";
		String college="Beautiful memories.";
		String classroom="Friends and juniors.";
		String home="Family !";
		String nativePlace="Sagar town.";
		String favouriteFood="All vegan food.";
		String phone="Redmi phone.";
		String laptop="Hp laptop.";
		String exam="Frustration.";
		String browser="Google Chrome.";
		String software="Java programming.";
		String library="World of books.";
		String englishAlphabets="ABCDEFGHIJKLMNOPQRSTUVWXYZ";
		String kannadaVarnamala="49";
		String actress="Anushka Sharma.";
		String actor="Shahid Kapoor.";
		String number="712";
		String color="Red, Black, Blue, Green.";
		String collegeName="UBDT College of Engineering.";
		String location="Davanagere.";
		String spectacles="Have it!";
		String music="Addicted and obsessed.";
		String selfLove="In love with myself.";
		String wannabe="Happiest person.";
		String visit="Kedarnath.";
		String language="Kannada.";
		String songs="Vibe to all.";
		String personaliy="Introvert.";
		String chocolates="Love it.";
		String cinema="Not a holic of movies.";
		String sibling="A Younger one.";
		String movie="Vivah.";
		String hairs="Short one.";
		String birthYear="2002";
		String age="22";
		String message2="How you doing!!";
		String coffee="And enjoy every sip of it";
		String foodie="And be healthy";
		String college2="With good people at college";
		String bestPart="They are the reason I go college to";
		String house="My people";
		String myTown="My comfort place !";
		String vegan="But I hate capsicum";
		String phoneBrand="Got it on my first year engineering!";
		String laptopBrand="Got it just a year ago";
		String test="That's what exams are of";
		String chrome="My browsing web";
		String programming="Starting to like it !";
		String book="Of course the library";
		String english="No of alphabets in English";
		String kannada="No of letters in Kannada";
		String actresses="One of my favourite actress";
		String actors="My most favourite actor";
		String mobNo="That's my number though!";
		String colors="My most favourite colors";
		String ubdt="The place where my most beautiful memories exist!!!";
		String city="- One of my fav places";
		String specs="Without these specs can't even go anywhere";
		String addicted="With music ";
		String love="Almost every single day";
		String be="With my people";
		String divine="The most divine place I wanna visit";
		String mothertongue="My comfort language";
		String vibe="To every song I listen to!";
		String trait="Haha extrovert to only my people";
		String choco="Never say no to chocolates!!";
		String holic="Coz 3 hrs is too long !";
		String younger="Cute little sister";
		String movie2="The best movie I have ever watched!!";
		String hairstyle="Like to keep my hairs short and now I want long hairs!!";
		String yearOfBirth="My Birth Year";
		String myAge="My age right now though I don't look like it !";
		String message3="Finally done";
		
		System.out.println(message1 + message2);
		System.out.println(drink + coffee);
		System.out.println(eat + foodie);
		System.out.println(college + college2);
		System.out.println(classroom + bestPart);
		System.out.println(home + house);
		System.out.println(nativePlace + myTown);
		System.out.println(favouriteFood + vegan);
		System.out.println(phone + phoneBrand);
		System.out.println(laptop + laptopBrand);
		System.out.println(exam + test);
		System.out.println(browser + chrome);
		System.out.println(software + programming);
		System.out.println(library + book);
		System.out.println(englishAlphabets + english);
		System.out.println(kannadaVarnamala + kannada);
		System.out.println(actress + actresses);
		System.out.println(actor + actors);
		System.out.println(number + mobNo);
		System.out.println(color + colors);
		System.out.println(collegeName + ubdt);
		System.out.println(location + city);
		System.out.println(spectacles + specs);
		System.out.println(music + addicted);
		System.out.println(selfLove + love);
		System.out.println(wannabe + be);
		System.out.println(visit + divine);
		System.out.println(language + mothertongue);
		System.out.println(songs + vibe);
		System.out.println(personaliy + trait);
		System.out.println(chocolates + choco);
		System.out.println(cinema + holic);
		System.out.println(sibling + younger);
		System.out.println(movie + movie2);
		System.out.println(hairs + hairstyle);
		System.out.println(birthYear + yearOfBirth);
		System.out.println(age + myAge);
		System.out.println(message3 + "not exactly");
		System.out.println(actor + "And his movie Vivah");
		System.out.println(actress + "Love her laugh");
		System.out.println(vibe + "Will be in my mind");
		System.out.println(selfLove + "like only me");
		System.out.println(hairstyle + "But missing my long hairs");
		System.out.println(exam + "And tension for exams");
		System.out.println(wannabe + "and some groovy music");
		System.out.println(cinema + "But love to watch some iconics");
		System.out.println(library + "And a bundle of knowledge");
		System.out.println(choco + "To anyone");
		System.out.println(divine + "Obviously with family");
		System.out.println(yearOfBirth + "2002 with the month mayyyyy");
		System.out.println(home + "Just love!");
		System.out.println(message1 + "Myself Keerthi Rao here!!");
		System.out.println(actresses + "And recently Kriti Sanon");
		System.out.println(language + "My language !");
		System.out.println(younger + "and also my lifeline!!");
		System.out.println("I'll eat all vegetables" + vegan);
		System.out.println(myAge + "Coz someone said it though!!");
		System.out.println(drink + "But no too much");
		System.out.println(movie + "The first ever movie of Shahid Kapoor");
		System.out.println(message1 + message2 + "And I'm doing great here !!");
		System.out.println(number + "It's actually my 4th number");
		System.out.println(addicted + "I can vibe with anyone");
		System.out.println(music + addicted + "Coz that's my passion");
		System.out.println(software + programming + "Coz it seems interesting");
		System.out.println(age + "That's just a number");
		System.out.println(yearOfBirth + birthYear + "somehow 2 is my lucky number");
		System.out.println(eat + "Coz health is wealth");
		System.out.println("love to be groovy" + be);
		System.out.println(test + "Checking our memory!");
		System.out.println(bestPart + "And that too to that class specially");
		System.out.println(phone + "Gotta take a new one!");
		System.out.println(chocolates + "That's the most craving thing for me" + choco);
		System.out.println(mothertongue + "And a bit of English too");
		System.out.println(message3 + "With this program");
		
	}
}